name: MinecraftCTF
main: com.deepwatercreations.minecraftctf.MinecraftCTF
version: 1
api-version: 1.16
commands:
  init:
    description: Initialize the game
    usage: /init
  ne:
    description: Change to the next particle effect
    usage: /ne
  respawnFlags:
    description: Respawn all flags in the game world
    usage: /respawnFlags
  teamlist:
    description: List the names of the teams
    usage: /teamlist
  teamjoin:
    description: Join a team
    usage: /teamlist [team name]
