name: MinecraftCTF
main: com.deepwatercreations.minecraftctf.MinecraftCTF
version: 1
api-version: 1.16
commands:
  init:
    description: Initialize the game
    usage: /init
  ne:
    description: Change to the next particle effect
    usage: /ne
